version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule: {interval: "daily"}
    open-pull-requests-limit: 8
    labels: ["dependencies"]
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
  - package-ecosystem: composer
    directory: "/backend"
    schedule: {interval: "daily"}
    open-pull-requests-limit: 8
    labels: ["dependencies"]
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
  - package-ecosystem: docker
    directory: "/deployment"
    schedule: {interval: "weekly"}
    open-pull-requests-limit: 8
    labels: ["dependencies"]
    groups:
      docker-images:
        applies-to: version-updates
  - package-ecosystem: docker
    directory: "/"
    schedule: {interval: "weekly"}
    open-pull-requests-limit: 8
    labels: ["dependencies"]
    groups:
      docker-images:
        applies-to: version-updates
