version: '3.8'
services:
  db:
    image: mariadb:10.11
    container_name: portal_db_local
    restart: unless-stopped
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: portal_db
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: admin
    volumes: ["db_data_local:/var/lib/mysql"]
  search:
    image: getmeili/meilisearch:v1.6
    container_name: portal_search_local
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: local_meili_secret
    ports: ["7700:7700"]
volumes:
  db_data_local:
